import Light from './Light';
import Camera from 'nanogl-camera';
import Bounds from './Bounds';
import PerspectiveLens from 'nanogl-camera/perspective-lens';
declare class SpotLight extends Light {
    private _innerAngle;
    private _outerAngle;
    private _radius;
    private _falloffCurve;
    _coneData: Float32Array;
    _falloffData: Float32Array;
    _camera: Camera<PerspectiveLens> | null;
    constructor();
    projectionFromBounds(bounds: Bounds): void;
    getTexelBiasVector(): Float32Array;
    _createCamera(): Camera<PerspectiveLens>;
    get innerAngle(): number;
    set innerAngle(v: number);
    get angle(): number;
    set angle(v: number);
    get outerAngle(): number;
    set outerAngle(v: number);
    get radius(): number;
    set radius(v: number);
    get falloffCurve(): number;
    set falloffCurve(v: number);
    _updateSpotData(): void;
    _updateFalloffData(): void;
}
export default SpotLight;
