import Input from './Input';
import Flag from './Flag';
import Precision from './ShaderPrecision';
import Version from './ShaderVersion';
import { GLContext } from 'nanogl/types';
import IBL from './Ibl';
import LightSetup from './LightSetup';
import Node from 'nanogl-node';
import Camera from 'nanogl-camera';
import { ICameraLens } from 'nanogl-camera/ICameraLens';
import { GammaModeEnum } from './GammaModeEnum';
import MaterialPass from './MaterialPass';
import Program from 'nanogl/program';
export default class StandardPass extends MaterialPass {
    ibl: IBL | null;
    version: Version;
    precision: Precision;
    iAlbedo: Input;
    iSpecular: Input;
    iGloss: Input;
    iNormal: Input;
    iOcclusion: Input;
    iCavity: Input;
    iCavityStrength: Input;
    iEmissive: Input;
    iEmissiveScale: Input;
    iFresnel: Input;
    iGamma: Input;
    iExposure: Input;
    conserveEnergy: Flag;
    perVertexIrrad: Flag;
    glossNearest: Flag;
    useDerivatives: Flag;
    gammaMode: GammaModeEnum;
    constructor(gl: GLContext, name?: string);
    setIBL(ibl: IBL): void;
    setLightSetup(setup: LightSetup): void;
    prepare(prg: Program, node: Node, camera: Camera<ICameraLens>): void;
}
