import GLConfig from 'nanogl-state/config';
import ProgramCache from './ProgramCache';
import Input from './Input';
import Flag from './Flag';
import Precision from './ShaderPrecision';
import Version from './ShaderVersion';
import ChunkCollection from './ChunkCollection';
import { GLContext } from 'nanogl/types';
import IBL from './Ibl';
import LightSetup from './LightSetup';
import Node from 'nanogl-node';
import Camera from 'nanogl-camera';
import { ICameraLens } from 'nanogl-camera/ICameraLens';
import Program from 'nanogl/program';
import { GammaModeEnum } from './GammaModeEnum';
export default class StandardMaterial {
    ibl: IBL | null;
    prg: Program | null;
    _prgcache: ProgramCache;
    _mask: number;
    inputs: ChunkCollection;
    version: Version;
    precision: Precision;
    shaderid: Flag;
    iAlbedo: Input;
    iSpecular: Input;
    iGloss: Input;
    iNormal: Input;
    iOcclusion: Input;
    iCavity: Input;
    iCavityStrength: Input;
    iEmissive: Input;
    iEmissiveScale: Input;
    iFresnel: Input;
    iGamma: Input;
    iExposure: Input;
    conserveEnergy: Flag;
    perVertexIrrad: Flag;
    glossNearest: Flag;
    useDerivatives: Flag;
    gammaMode: GammaModeEnum;
    config: GLConfig;
    _vertSrc: string;
    _fragSrc: string;
    constructor(gl: GLContext);
    setIBL(ibl: IBL): void;
    setLightSetup(setup: LightSetup): void;
    prepare(node: Node, camera: Camera<ICameraLens>): void;
    _isDirty(): boolean;
    getProgram(): Program;
    compile(): void;
}
